### ISSUE TITLE
Header z-index is wrong

### ISSUE THREAD

**Issue by ugnelis** [Edvinas01/meme-grid#16]
When I hover on image, it appears on top the header. I think it's the problem with CSS z-index.

![Bug](https://user-images.githubusercontent.com/8350893/39747156-c26235da-52ac-11e8-8d70-76959d6c7c41.png)

Cheers!

**Comment by Edvinas01** [comment]
This is by design, see:
https://github.com/Edvinas01/meme-grid/blob/master/src/main/resources/public/static/index.css#L4

**Comment by ugnelis** [comment]
Not good design :(

**Comment by Edvinas01** [comment]
@ugnelis maybe you could propose an alternative and create a PR :wink:

**Comment by ugnelis** [comment]
Kada nors, seniukas :D
