### ISSUE TITLE
Use Kotlin DSL

### ISSUE THREAD

**Issue by Edvinas01** [Edvinas01/meme-grid#26]
`build.gradle` should be converted to Kotlin and renamed to `build.gradle.kts`.

For more info see:
https://docs.gradle.org/current/userguide/kotlin_dsl.html

**Comment by azisuazusa** [comment]
@Edvinas01 will work on this issue

**Comment by Edvinas01** [comment]
Closed with https://github.com/Edvinas01/meme-grid/pull/38
