### ISSUE TITLE
Add static code analysis

### ISSUE THREAD

**Issue by Edvinas01** [Edvinas01/meme-grid#28]
Add static code analysis. It should be run after tests - that is after running the `check` task, tests and then static code analysis should run in order.

Detekt seems like a good choice:
https://github.com/arturbosch/detekt

**Comment by norangebit** [comment]
Can I try to work on this?

**Comment by Edvinas01** [comment]
Sure thing!

**Comment by norangebit** [comment]
I sent you a [pull request](https://github.com/Edvinas01/meme-grid/pull/34).
