### ISSUE TITLE
Sort memes by day

### ISSUE THREAD

**Issue by ugnelis** [Edvinas01/meme-grid#8]
In my opinion, it would be nice to memes sorting feature. That also would decrease chance to see same meme many times. 

Cheers!

**Comment by Edvinas01** [comment]
Memes are sorted by ids. Each new meme gets an new id which is higher than the previous one. Idea is that you'll only be seeing around 100 or so latest memes. So you'll never see duplicates.

Also there is a unique constraint on meme url, so you shouldn't be seeing dupes.

**Comment by ugnelis** [comment]
@Edvinas01 oh I see. Thank you
